name: Build and Attach Release

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      version:
        description: "Version to release (e.g., v1.0.0)"
        required: false

jobs:
  build-and-upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          make build

      - name: Get artifact file
        id: get_artifact
        run: |
          file=$(ls dist/*.whl | head -n 1)
          echo "file=$file" >> $GITHUB_ENV
          echo "filename=$(basename $file)" >> $GITHUB_ENV

      - name: Create release (if manual dispatch)
        if: github.event_name == 'workflow_dispatch'
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.event.inputs.version }}
          release_name: ${{ github.event.inputs.version }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload artifact to release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url || steps.create-release.outputs.upload_url }}
          asset_path: ${{ env.file }}
          asset_name: ${{ env.filename }}
          asset_content_type: application/zip
